### ISSUE TITLE
More customisability of the tools & weapons

### ISSUE THREAD

**Issue by sormgoma** [xanthian/expert_weapons#11]
Hello, I'm not too sure if this is out of the scope of this mod but I think introducing different types of hilts/bindings and handles which give different modifiers to the final tool would be really interesting. First and foremost the material would be taken into account, for example a hilt of a stronger heavier metal could give you a slightly slower attack speed (due to its weight), but a higher chance of defending an attack from another sword. Maybe a type of hilt better against axes due to its shape. As for the handle maybe a better grip, preventing potential miss-swings (requiring you to add miss-swings). This might end up too close to a play on bettercombat, but more vanilla like ; maybe an addon would be more appropriate. 

Also, maybe modifiers for the actual blade/head in a tinker-esque style would be fitting, such as quartz = sharpness. I think this would really make a tool more personal which is great !

**Comment by xanthian** [comment]
sounds like tinkers construct to me.
not planning on adding any features such as these in the near future I'm afraid.
