### ISSUE TITLE
shovel and axe recipes?

### ISSUE THREAD

**Issue by pinchese** [xanthian/expert_weapons#3]
so apparently the shovel head makes an axe?? and to make a shovel you use a smithing table? is this supposed to happen? it's a little bit funny but a little weird too

mc version is 1.18.2

**Comment by xanthian** [comment]
please elaborate...

**Comment by pinchese** [comment]
![image](https://user-images.githubusercontent.com/82222883/177406642-9c5a6659-a495-49f8-854c-34784288035c.png)
this happens for literally every axe tier above stone
and shovels can only be made in a smithing table
![image](https://user-images.githubusercontent.com/82222883/177406766-a1b62712-8f96-439b-ad48-9b8f06026f20.png)

**Comment by xanthian** [comment]
mod list please

**Comment by pinchese** [comment]
it's pretty big
![image](https://user-images.githubusercontent.com/82222883/177412984-34884952-b865-4157-9225-1a00fad06813.png)

**Comment by xanthian** [comment]
should be sorted now.. how that got missed I don't know.

Will upload to CF shortly.

**Comment by xanthian** [comment]
https://www.curseforge.com/minecraft/mc-mods/expert-weapons/files/3866697
