### ISSUE TITLE
[Request] Compat for Advanced Netherite Mod

### ISSUE THREAD

**Issue by cymophic** [xanthian/expert_weapons#4]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/advanced-netherite

**Comment by xanthian** [comment]
Started on this, but a little perplexed how to proceed.
Take the Axe for example, it currently requires 6 Netherite to make.
Should the Advanced ones take a further 6?

**Comment by cymophic** [comment]
I think its fine as long as its the same with all the other tools. Maybe tune down the 6 since the mod only upgrades already-built netherite tools and weapons?

**Comment by xanthian** [comment]
Made a start
![image](https://user-images.githubusercontent.com/7688001/183258231-b38081bc-2289-4647-a6a9-df8d0ea9aa4f.png)

Still thinking how to do the recipes.

**Comment by xanthian** [comment]
Recipes will require 1 Advanced Netherite Ingot to make the dull part and 1 to make the whetstone.
As well as requiring normal Netherite.
eg..

![image](https://user-images.githubusercontent.com/7688001/183293394-1e9b9cf5-b62e-49dc-afdf-7cd4636b1bc2.png)
![image](https://user-images.githubusercontent.com/7688001/183293410-6296c32d-7fb5-42e2-9bd4-fc490e0e90a3.png)
![image](https://user-images.githubusercontent.com/7688001/183293431-7644e800-8646-47ba-9fac-895921d43175.png)

This is open for discussion, but will be released like this.

**Comment by cymophic** [comment]
Lookin' good already, and the adjustments on the sprites are well-made. For now, we could just wait for the other's feedback for any other adjustments. Overall, I'm contented with the amount of netherite needed to craft the stuff. Thanks for the update!

P.s. Someone really needs to work on that whetstone texture xD

**Comment by xanthian** [comment]
Is that an offer? 😉
