### ISSUE TITLE
[Mod Compat] Medieval Weapons

### ISSUE THREAD

**Issue by CasualJeremy** [xanthian/expert_weapons#7]
Would it be possible to add compatibility with this mod?

https://www.curseforge.com/minecraft/mc-mods/medievalweapons

**Comment by xanthian** [comment]
can certainly look at it, will let you know.

**Comment by xanthian** [comment]
That is A LOT of weapons.
No promises, but i'll plan this in.

**Comment by CasualJeremy** [comment]
Yeah that's true, but I appreciate it!

**Comment by xanthian** [comment]
Made a start on it, but looks like the mod is going through some big changes atm, so will wait for the 1.19.2 release before I progress too far.

**Comment by CasualJeremy** [comment]
Okay, seems like a lot of mods are getting compats in 1.19.2 which is amazing, thanks again!
