### ISSUE TITLE
Incorrect Models

### ISSUE THREAD

**Issue by Shadowdragon019** [xanthian/expert_weapons#8]
### First person - Main-hand
![2022-08-25_14 26 32](https://user-images.githubusercontent.com/67480398/186751398-83d9a82b-819e-46c0-9a60-890a19e880d9.png)
### Third person - Any-hand
![2022-08-25_14 26 35](https://user-images.githubusercontent.com/67480398/186751402-d9ab091c-4ee2-4efe-a3f2-0825abb39a8c.png)

**Comment by xanthian** [comment]
1st image, main hand looks fine?
Presumably you meant offhand.
What other mods are installed

**Comment by xanthian** [comment]
Any more info?

**Comment by xanthian** [comment]
Lack of info. Closing
