### ISSUE TITLE
Crash when enchanting

### ISSUE THREAD

**Issue by Bill-McKenty** [xanthian/expert_weapons#9]
Hello, i noticed the game crash when trying to enchant a weapon that has an integrated enchantement, for exemple the master katana that has critical hit I on it will make the game crash when trying to enchant on an anvil.

**Comment by xanthian** [comment]
I have no anvil interactions nor any katana's in this mod.
You'll have to provide crash log and more information, im not a mind reader not a wizard

**Comment by xanthian** [comment]
Anything to add?

**Comment by Bill-McKenty** [comment]
It's for the Medieval minecraft fabric modpack 1.19.3, more precisely the minecraft dongeon weapons mod, but i saw that this issue was reported elsewhere already, not sure if i'm at the right place...

**Comment by xanthian** [comment]
Closing this as to little information to act on.
